<?php
/**
 * Created by PhpStorm.
 * User: langa
 * Date: 5/11/2018
 * Time: 11:44 AM
 */
include 'includes/DB.php';
include 'helpers/Response.php';


if(!empty($_POST['function']))
    $function = $_POST['function'];

if(!empty($_GET['function']))
    $function = $_GET['function'];

if(!empty($_POST['function']))
    $function = $_POST['checkout'];

if(!empty($_REQUEST['function']))
    $function = $_REQUEST['function'];


    
function referenceCode(){
    $today = date("d");
    $rand = strtoupper(substr(uniqid(sha1(time())),0,4));

    return $unique = $today . $rand;
}



if($function=='checkout'){
    $amount=$_REQUEST['amount'];
    $amount = number_format($amount, 2);//format amount to 2 decimal places
    $desc = $_REQUEST['description'];
    $type = $_REQUEST['type']; //default value = MERCHANT
    $referenceCode = referenceCode();//unique order id of the transaction, generated by merchant
    $first_name = $_REQUEST['first_name']; //[optional]
    $last_name = $_REQUEST['last_name']; //[optional]
    $email = $_REQUEST['email'];
    $phonenumber =$_REQUEST['phonenumber']; //ONE of email or phonenumber is required



    $sql="INSERT INTO `payments`(`referencecode`, `amount`, `email`, `phone_no`, `firstname`, `lastname`)
                VALUES ('$referenceCode','$amount','$email','$phonenumber','$first_name','$last_name')";


    $result = DB::instance()->executeSQL($sql);

    if($result){

        $response = new Response();
        $response->status = Response::STATUS_SUCCESS;
        $response->message= "success";
        $response->success = true;
        echo json_encode($response);
        exit();
    }else{

        $response = new Response();
        $response->status = Response::STATUS_SUCCESS;
        $response->message= "failed";
        $response->success = false;
        echo json_encode($response);
        exit();
    }


}